// <auto-generated />
using System;
using EF_Assignment_3.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Assignment_3.Migrations
{
    [DbContext(typeof(AirLineDbContext))]
    [Migration("20251122011629_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Assignment_3.Entities.AirCraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirLineId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirLineId");

                    b.ToTable("AirCrafts");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.AirCraftRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirCraftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("NumOfPassengers")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirCraftId");

                    b.HasIndex("RouteId");

                    b.ToTable("AirCraftRoutes");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.AirLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AirLines");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.AirLinePhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirLineId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirLineId");

                    b.ToTable("AirLinePhones");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Crew", b =>
                {
                    b.Property<int>("AirCraftId")
                        .HasColumnType("int");

                    b.Property<int>("AssistPilotId")
                        .HasColumnType("int");

                    b.Property<int>("Host1Id")
                        .HasColumnType("int");

                    b.Property<int>("Host2Id")
                        .HasColumnType("int");

                    b.Property<int>("MajorPilotId")
                        .HasColumnType("int");

                    b.HasKey("AirCraftId");

                    b.HasIndex("AssistPilotId");

                    b.HasIndex("Host1Id");

                    b.HasIndex("Host2Id");

                    b.HasIndex("MajorPilotId");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirLineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirLineId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.EmployeeQualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeQualifications");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classfication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Orgin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirLineId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.AirCraft", b =>
                {
                    b.HasOne("EF_Assignment_3.Entities.AirLine", "AirLine")
                        .WithMany("AirCrafts")
                        .HasForeignKey("AirLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AirLine");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.AirCraftRoute", b =>
                {
                    b.HasOne("EF_Assignment_3.Entities.AirCraft", "AirCraft")
                        .WithMany("AirCraftRoutes")
                        .HasForeignKey("AirCraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Assignment_3.Entities.Route", "Route")
                        .WithMany("AirCraftRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirCraft");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.AirLinePhone", b =>
                {
                    b.HasOne("EF_Assignment_3.Entities.AirLine", "AirLine")
                        .WithMany("Phones")
                        .HasForeignKey("AirLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirLine");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Crew", b =>
                {
                    b.HasOne("EF_Assignment_3.Entities.AirCraft", "AirCraft")
                        .WithOne("Crew")
                        .HasForeignKey("EF_Assignment_3.Entities.Crew", "AirCraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Assignment_3.Entities.Employee", "AssistPilot")
                        .WithMany("AssistPilots")
                        .HasForeignKey("AssistPilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EF_Assignment_3.Entities.Employee", "Host1")
                        .WithMany("Host1s")
                        .HasForeignKey("Host1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EF_Assignment_3.Entities.Employee", "Host2")
                        .WithMany("Host2s")
                        .HasForeignKey("Host2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EF_Assignment_3.Entities.Employee", "MajorPilot")
                        .WithMany("MajorPilots")
                        .HasForeignKey("MajorPilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AirCraft");

                    b.Navigation("AssistPilot");

                    b.Navigation("Host1");

                    b.Navigation("Host2");

                    b.Navigation("MajorPilot");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Employee", b =>
                {
                    b.HasOne("EF_Assignment_3.Entities.AirLine", "AirLine")
                        .WithMany("Employees")
                        .HasForeignKey("AirLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AirLine");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.EmployeeQualification", b =>
                {
                    b.HasOne("EF_Assignment_3.Entities.Employee", "Employee")
                        .WithMany("Qualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Transaction", b =>
                {
                    b.HasOne("EF_Assignment_3.Entities.AirLine", "AirLine")
                        .WithMany("Transactions")
                        .HasForeignKey("AirLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirLine");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.AirCraft", b =>
                {
                    b.Navigation("AirCraftRoutes");

                    b.Navigation("Crew")
                        .IsRequired();
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.AirLine", b =>
                {
                    b.Navigation("AirCrafts");

                    b.Navigation("Employees");

                    b.Navigation("Phones");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Employee", b =>
                {
                    b.Navigation("AssistPilots");

                    b.Navigation("Host1s");

                    b.Navigation("Host2s");

                    b.Navigation("MajorPilots");

                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("EF_Assignment_3.Entities.Route", b =>
                {
                    b.Navigation("AirCraftRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
